version: '3'
services:
  myapp:
    image: 'bitnami/codeigniter:3'
    ports:
      - '8000:8000'
    volumes:
      - '.:/app'
  mariadb:
    image: 'bitnami/mariadb:10.3'
    volumes:
       - './mariadb-persistence:/bitnami/mariadb'
    environment:

      - MARIADB_DATABASE=nutricion_tesis    
